### PR TITLE
Some fixes that I found during testing

### PR DESCRIPTION
**Pull request by Flova**
- Typo in the obstacle topic
- Object origin for 3D vision bounding boxes is in the center of the object and not on the field plane

### CODE REVIEW

**Review by ijnek — APPROVED** [review]

**Comment by ijnek** [comment]
Test failure seems unrelated, and should be eliminated by #5

**Comment by Flova** [comment]
> Test failure seems unrelated, and should be eliminated by #5

We should still have a look at the IPM service to see what's wrong.

**Comment by ijnek** [comment]
Yes, we should. I wonder if its an issue that is hard to reproduce...

**Comment by ijnek** [comment]
Moved it to a new issue: https://github.com/ros-sports/ipm/issues/50

**Pull request merged**
